### ISSUE TITLE
Feature Proposal: Support for Displaying Foreign Currencies (e.g., Euro)

### ISSUE THREAD

**Issue by jackthomasanderson** [hargata/lubelog_translations#19] opened 2024-02-15 17:54 UTC
I'm writing to propose a new feature for LubeLogger that I believe would greatly benefit users, particularly those operating in regions where currencies other than the default are commonly used.

The proposal involves incorporating functionality into LubeLogger to allow users to view currency values in foreign denominations, such as the Euro (€), alongside the default currency. This feature would enhance the versatility of the application and make it more accessible to users across various regions.

Currency Selection: Users should be able to select their preferred currency from a list of supported options within the app's settings.

Thank you for considering this proposal. 

Regards

**Comment by 6asc** [comment] 2024-02-17 18:04
Duplicate of hargata/lubelog#298 (misconfigured locale)

**Closed** 2024-10-17 23:15 UTC
